### ISSUE TITLE
[TASK] Add event metadata to the Index

### ISSUE THREAD

**Issue by SicorDev** [derhansen/sf_event_mgt_indexer#20]
Hi there,

just had a customer asking why the metas he entered aren't found via ke_search. Would be cool if you could add them.
I hacked it like this for the moment:

$metas = strip_tags($event['meta_keywords']);
$fullContent = $metas . "\n" . $title . "\n" . $teaser . "\n" . $content . "\n" . $program;

Greetings,
Manuel

**Comment by derhansen** [comment]
Thanks for your report. I will add keywords and other metadata to the index in the next release of the extension (TYPO3 v11 and v12 support only).

**Comment by derhansen** [comment]
Feature has been added to version 4.0 (which support TYPO3 v11 and v12).
