### ISSUE TITLE
 strip_tags() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by KHReinhardt** [derhansen/sf_event_mgt_indexer#21]
Hi there,

I am testing an update to version 4.0.0 on typo3 11.5.27 and I get the following Error:
TypeError, code #0, file \typo3conf\ext\sf_event_mgt_indexer\Classes\Indexer\EventIndexer.php, line 74: strip_tags(): Argument #1 ($string) must be of type string, null given

sf_event_mgt 6.4.1
ke_search 4.6.5

**Comment by derhansen** [comment]
Thanks for your report. I can not really reproduce the problem, since the `teaser` field should never be `null`. Do you have the same problem with version 3.x of the extension?

**Comment by KHReinhardt** [comment]
Thank you for your quick reply. 
I have version 3.0.2 with sf_event_mgt 6.3.1 running on productive with no problems. With a 3.0.2 and sf_event_mgt 6.4.1 on a test instance, I encountered no problems as well.
I also checked the databases and almost half of the entries in the table tx_sfeventmgt_domain_model_event do have `null` in the `teaser` column (in all our typo3 instances).

**Comment by derhansen** [comment]
I still have no idea why this worked in version 3.0.2, since in that version, there is no null value check either. However, I now added a null check for all `text` fields and released version 4.0.1 of the extension. Feel free to provide feedback, if you still get errors.

**Comment by KHReinhardt** [comment]
I've tested v. 4.0.1., no errors and the indexer works like a charm now. You provide outstanding support, thank you!
