### ISSUE TITLE
Show startdate and enddate instead of timestamp

### ISSUE THREAD

**Issue by ste101** [derhansen/sf_event_mgt_indexer#24]
Search result shows timestamp of event.
Betterwould be start- and enddate.

If the key would be exactly the same as the corresponding table name date fields could be accessed via resultrow.orig_row.xxx.
https://docs.typo3.org/p/tpwd/ke_search/5.0/en-us/Templating/CustomValuesResultRow.html?highlight=orig_row#accessing-the-original-database-row

Or would it be better to add extra fields for startdate and enddate?

**Comment by derhansen** [comment]
Extra fields (timestamps for start- and enddate) is the option to go here. I've seen some projects, where integrators use a custom ViewHelper to retrieve the full event record in order to render startdate, enddate and various other event related data.

**Comment by derhansen** [comment]
The extension was wrong and used the event creation date for sortdate in the indexer. This has now been fixed. If you want to show other event related fields, I suggest you either use the `ModifyIndexDataEvent` to enrich the index with additional fields or to use a custom ViewHelper to fetch the event record and to display required information.
