### ISSUE TITLE
[FEATURE] Is it possible that registration pages can also be indexed?

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt_indexer#26]
From the Listview we directly go to the "detail page" which has a registration formular, so it's not the actual detail page, it's the registration page with information of the event.
We noticed, that in our search results the urls for those events are with parameters and if you click on one, you get a 404-error.

Usually the slug should be speaking slugs, that is why we noticed it.

This works for other pages where we have a real detail page before the registration page.

We think it's because the indexer only takes into account the detail page and not the registration page.
https://github.com/derhansen/sf_event_mgt_indexer/blob/d8b8d6d5f156de7e51e50b18540e2c4f37f08540/Classes/Indexer/EventIndexer.php#L81

We changed it with a condition to
```
$params = '&tx_sfeventmgt_pieventregistration[action]=registration&tx_sfeventmgt_pieventregistration[controller]=Event&tx_sfeventmgt_pieventregistration[event]=' . $event['uid'];
```
so that the `&tx_sfeventmgt_pieventregistration[action]=registration` part is also included.

But this involved a custom variable that is not available in the event extension.

**My question**
Is it possible to extend the EventIndexer so that the registration page is also indexed and appears correctly in the search results?

**Some suggestions**
- in targetpid you can either select the Detail or Registration page and the depending on the used plugin on the page, $params changes (not sure if that is possible)
- a checkbox where you can choose if the targetpid is either a detailPage or registrationPage and depending on the selection, $params changes
- another page select field targetpidRegistration where you can select a registration page

**Comment by derhansen** [comment]
Basically the described is possible by extending the indexer configuration and then adding the condition. I would prefer to have a new select field in the indexer config, which details to the value `0` (label: `Target page is event detail page`) and which has a 2nd select item with the value `1`(label: `Target page is event registration page`). Having this in place, the condition can easily be added. 

Feel free to provide a PR for this.

**Comment by medarob** [comment]
Mh, how do I add another field like `targetpid`? Where do you add the `targetpid` field in the indexer extension? I don't see it. 😅

**Comment by derhansen** [comment]
`targetpid` is standard for an indexer and must not be added. Please refer to ke_search documentation for details on adding custom fields. As an alternative, I can implement the feature for a small sponsoring ;-)

**Comment by derhansen** [comment]
Since there is no progress in this issue, I will now close it.
