### ISSUE TITLE
Update from 1.0.3 to 2.x on TYPO3 8.7.24 not possible via backend

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt_indexer#8]
Hi,

I came across an issue when I wanted to update the extension in the TYPO3 backend.

### Extension version
sf_event_mgt: 3.0.8
ke_search indexer for sf_event_mgt 1.0.3

### Short problem description
I wanted to update the ke_search indexer to a newer version but I there is no indication in the backend, that a newer version is available.

![grafik](https://user-images.githubusercontent.com/33951787/56789714-d8eaca80-6802-11e9-8dce-aa991bb2f585.png)

### Expected behaviour
I should see the update icon, that a newer version is available.

### Actual behaviour
No update icon available... I guess I only can update the extension manually? Haven't tried it yet because I wanted to report that issue first.

### Server configuration
**TYPO3 version:** TYPO3 8.7.24

**PHP version:** 7.2

**Comment by derhansen** [comment]
Manual update will fail, since I added a dependency to ext:ke_search version 3.x, which is TYPO3 9.5 only. I need to change some code in order to make the indexer execute on TYPO3 8.7 and 9.5

**Comment by derhansen** [comment]
Fixed with f3e319eaf8f138ad9e06f0a9252ec94b2180f6a0
