### ISSUE TITLE
Wrong Array-Key

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt_indexer#9]
There is a dollar-character in the array-key-reference which prevents the indexer from indexing the field "program" at all. This typo exists since version 1.x. ;)

-> $event['$program'] must be $event['program']

https://github.com/derhansen/sf_event_mgt_indexer/blob/7c1fece59071b87a82fead51a74c00112244b1f7/Classes/Indexer/EventIndexer.php#L77

**Comment by derhansen** [comment]
Damn copy&paste actions ;-) Thanks a lot for reporting. Will fix the issue asap.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
If you need assistance to remove the character, let me know. :-P
